# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ICtDkfo5I1RYICkmfFXuCLzrR61iIVj6
"""

import streamlit as st
import pickle

model = pickle.load(open("model.pkl", "rb"))
vectorizer = pickle.load(open("vectorizer.pkl", "rb"))

st.set_page_config(
    page_title="Letterboxd Sentiment Analyzer",
    page_icon="🎬",
    layout="centered"
)

st.title("🎬 Letterboxd Review Analyzer")
st.markdown("Write your movie review and discover the vibe ✨")
st.markdown("---")

review = st.text_area("Your Review", height=200)

if st.button("Analyze Review"):
    if review:
        review_vectorized = vectorizer.transform([review])
        prediction = model.predict(review_vectorized)
        probability = model.predict_proba(review_vectorized)

        confidence = max(probability[0]) * 100

        if prediction[0] == "positive":
            st.success(f"⭐ Positive Vibes ({confidence:.2f}% confidence)")
        else:
            st.error(f"💔 Negative Vibes ({confidence:.2f}% confidence)")
    else:
        st.warning("Please write a review first.")